"""empty message

Revision ID: 50e26fe01a9e
Revises: 4a3b020205b8
Create Date: 2020-07-03 11:10:35.582445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50e26fe01a9e'
down_revision = '4a3b020205b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('image', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry', 'image')
    # ### end Alembic commands ###
