"""empty message

Revision ID: 924f0de98a89
Revises: 4a3b020205b8
Create Date: 2020-07-04 11:38:54.384588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '924f0de98a89'
down_revision = '4a3b020205b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('image_url', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry', 'image_url')
    # ### end Alembic commands ###
